export type CuratedSeed = {
  slug: string;
  displayName: string;
  description: string;
  tags: string[];
  aliases?: string[];
};

export const CURATED_SEEDS: CuratedSeed[] = [
  { slug: 'gotham-chaos', displayName: 'Gotham Chaos', description: 'A dark tactical setup with early queen pressure.', tags: ['chaos', 'tactical'], aliases: ['otham-chaos'] },
  { slug: 'boss-battle', displayName: 'Boss Battle', description: 'A direct challenge seed for competitive rematches.', tags: ['challenge', 'hard'] },
  { slug: 'rook-rage', displayName: 'Rook Rage', description: 'Rooks hit open lanes early and punish slow development.', tags: ['rook', 'attack'] },
  { slug: 'queen-panic', displayName: 'Queen Panic', description: 'Queen pressure starts loud and forces immediate defensive choices.', tags: ['queen', 'chaos'] },
  { slug: 'rook-trap', displayName: 'Rook Trap', description: 'Rooks become tempting targets early.', tags: ['trap', 'rook'] },
  { slug: 'queen-rush', displayName: 'Queen Rush', description: 'Queen activity appears early, but greed can backfire.', tags: ['queen', 'fast'] },
  { slug: 'knight-panic', displayName: 'Knight Panic', description: 'Knight jumps create instant tactical threats.', tags: ['knight', 'tactics'] },
  { slug: 'bishop-storm', displayName: 'Bishop Storm', description: 'Diagonal pressure builds quickly.', tags: ['bishop', 'attack'] },
  { slug: 'pawn-wall', displayName: 'Pawn Wall', description: 'A cramped setup that rewards pawn timing.', tags: ['pawn', 'positional'] },
  { slug: 'no-mercy', displayName: 'No Mercy', description: 'A ruthless seed where loose pieces disappear quickly.', tags: ['hard', 'capture'] },
  { slug: 'tiny-war', displayName: 'Tiny War', description: 'A compact battlefield with no slow opening phase.', tags: ['fast', 'compact'] },
  { slug: 'bishop-trap', displayName: 'Bishop Trap', description: 'Diagonal bait sets up quick tactical punishment.', tags: ['bishop', 'trap'] },
  { slug: 'knightmare', displayName: 'Knightmare', description: 'Knight jumps turn the tiny board into a tactical nightmare.', tags: ['knight', 'tactics'] },
  { slug: 'mirror-madness', displayName: 'Mirror Madness', description: 'Same material, strange symmetry, sharp tactics.', tags: ['mirror', 'chaos'] },
  { slug: 'crown-hunt', displayName: 'Crown Hunt', description: 'The king becomes vulnerable faster than expected.', tags: ['king', 'attack'] },
  { slug: 'blitz-cave', displayName: 'Blitz Cave', description: 'A fast seed built for short tactical games.', tags: ['blitz', 'fast'] },
  { slug: 'trap-door', displayName: 'Trap Door', description: 'One careless capture opens the board.', tags: ['trap', 'tactical'] },
  { slug: 'fork-factory', displayName: 'Fork Factory', description: 'Knight and queen forks appear often.', tags: ['fork', 'tactics'] },
  { slug: 'check-rush', displayName: 'Check Rush', description: 'Early checks can snowball into mate threats.', tags: ['check', 'attack'] },
  { slug: 'checkmate-me', displayName: 'Checkmate Me', description: 'A daring seed for players who want immediate mate threats.', tags: ['mate', 'challenge'] },
  { slug: 'queen-bait', displayName: 'Queen Bait', description: 'The queen looks powerful, but can become a target.', tags: ['queen', 'trap'] },
  { slug: 'rook-rumble', displayName: 'Rook Rumble', description: 'Rooks fight for open files quickly.', tags: ['rook', 'battle'] },
  { slug: 'bishop-bite', displayName: 'Bishop Bite', description: 'Diagonal captures decide the pace.', tags: ['bishop', 'capture'] },
  { slug: 'knight-cage', displayName: 'Knight Cage', description: 'Knight mobility is the key puzzle.', tags: ['knight', 'puzzle'] },
  { slug: 'pawn-break', displayName: 'Pawn Break', description: 'Pawn captures open dangerous lanes.', tags: ['pawn', 'tactical'] },
  { slug: 'royal-mess', displayName: 'Royal Mess', description: 'The king starts safe, but not for long.', tags: ['king', 'chaos'] },
  { slug: 'mini-mayhem', displayName: 'Mini Mayhem', description: 'A chaotic tiny-board fight.', tags: ['chaos', 'fast'] },
  { slug: 'sharp-corners', displayName: 'Sharp Corners', description: 'Edge squares matter more than they seem.', tags: ['board', 'tactics'] },
  { slug: 'center-crush', displayName: 'Center Crush', description: 'Control the center or get squeezed.', tags: ['center', 'positional'] },
  { slug: 'side-swipe', displayName: 'Side Swipe', description: 'Side attacks arrive faster on the 5x6 board.', tags: ['flank', 'attack'] },
  { slug: 'backrank-brawl', displayName: 'Backrank Brawl', description: 'Back-rank piece order creates immediate tension.', tags: ['backrank', 'battle'] },
  { slug: 'chaos-crown', displayName: 'Chaos Crown', description: 'A messy setup where king safety decides everything.', tags: ['chaos', 'king'] },
  { slug: 'silent-fork', displayName: 'Silent Fork', description: 'Quiet moves create brutal forks.', tags: ['fork', 'puzzle'] },
  { slug: 'fast-mate', displayName: 'Fast Mate', description: 'Built for players hunting quick checkmates.', tags: ['mate', 'fast'] },
  { slug: 'narrow-board', displayName: 'Narrow Board', description: 'The small width creates forced confrontations.', tags: ['compact', 'strategy'] },
  { slug: 'queen-corner', displayName: 'Queen Corner', description: 'Queen placement changes the whole opening fight.', tags: ['queen', 'positional'] },
  { slug: 'rook-road', displayName: 'Rook Road', description: 'Open lanes decide the winner.', tags: ['rook', 'lane'] },
  { slug: 'bishop-lane', displayName: 'Bishop Lane', description: 'Diagonal lanes are unusually important.', tags: ['bishop', 'lane'] },
  { slug: 'knight-jump', displayName: 'Knight Jump', description: 'Jump tactics appear almost immediately.', tags: ['knight', 'fast'] },
  { slug: 'pawn-chaos', displayName: 'Pawn Chaos', description: 'Pawns create messy tactical openings.', tags: ['pawn', 'chaos'] },
  { slug: 'king-sprint', displayName: 'King Sprint', description: 'The king may need to move earlier than expected.', tags: ['king', 'survival'] },
  { slug: 'tactical-tiny', displayName: 'Tactical Tiny', description: 'Small board, big tactical punishment.', tags: ['tactical', 'compact'] },
  { slug: 'daily-dragon', displayName: 'Daily Dragon', description: 'A spicy seed for daily challenge sharing.', tags: ['daily', 'attack'] },
  { slug: 'brain-brawl', displayName: 'Brain Brawl', description: 'A seed designed for score battles.', tags: ['challenge', 'score'] },
  { slug: 'no-book', displayName: 'No Book', description: 'Opening theory is useless here.', tags: ['anti-opening', 'tactical'] },
  { slug: 'fresh-opening', displayName: 'Fresh Opening', description: 'A new opening puzzle every time.', tags: ['opening', 'puzzle'] },
  { slug: 'seed-slayer', displayName: 'Seed Slayer', description: 'Built for beat-my-score sharing.', tags: ['challenge', 'viral'] },
  { slug: 'mate-hunter', displayName: 'Mate Hunter', description: 'Checkmate threats appear quickly.', tags: ['mate', 'attack'] },
  { slug: 'capture-race', displayName: 'Capture Race', description: 'Material swings fast.', tags: ['capture', 'score'] },
  { slug: 'score-chase', displayName: 'Score Chase', description: 'Optimized for chasing higher points.', tags: ['score', 'replay'] },
  { slug: 'friend-duel', displayName: 'Friend Duel', description: 'Best used as a direct friend challenge.', tags: ['friend', 'duel'] },
  { slug: 'revenge-seed', displayName: 'Revenge Seed', description: 'Lose once, replay, and send it back.', tags: ['rematch', 'challenge'] },
  { slug: 'rage-quit', displayName: 'Rage Quit', description: 'A volatile setup built for dramatic swings and instant rematches.', tags: ['chaos', 'rematch'] },
  { slug: 'tiny-tactics', displayName: 'Tiny Tactics', description: 'A clean tactical seed for quick games.', tags: ['tactics', 'fast'] },
  { slug: 'wild-mirror', displayName: 'Wild Mirror', description: 'Mirrored fairness with chaotic outcomes.', tags: ['mirror', 'chaos'] },
  { slug: 'opening-zero', displayName: 'Opening Zero', description: 'No memorized opening survives this setup.', tags: ['anti-opening', 'fresh'] },
  { slug: 'final-boss', displayName: 'Final Boss', description: 'A hard-looking seed made for bragging rights.', tags: ['hard', 'challenge'] },
  { slug: 'fork-frenzy', displayName: 'Fork Frenzy', description: 'Fork threats arrive early and force awkward choices.', tags: ['fork', 'tactics'] },
  { slug: 'queen-tilt', displayName: 'Queen Tilt', description: 'Queen pressure creates unstable positions from move one.', tags: ['queen', 'attack'] },
  { slug: 'rook-riot', displayName: 'Rook Riot', description: 'Rooks crash through files in a noisy tactical race.', tags: ['rook', 'chaos'] },

  { slug: 'hikaru-speedrun', displayName: 'Hikaru Speedrun', description: 'A lightning-fast creator seed packed with pre-move tactics.', tags: ['chess', 'streamer', 'blitz', 'creator'], aliases: ['hikaru', 'gmhikaru'] },
  { slug: 'magnus-endgame', displayName: 'Magnus Endgame', description: 'A champion-style grind where tiny advantages become lethal.', tags: ['chess', 'champion', 'endgame', 'creator'], aliases: ['magnus', 'carlsen'] },
  { slug: 'botez-gambit', displayName: 'Botez Gambit', description: 'A chaotic queen-side seed made for dramatic saves and sacrifices.', tags: ['chess', 'streamer', 'gambit', 'creator'], aliases: ['botez', 'alexandra-botez', 'andrea-botez'] },
  { slug: 'ana-checkstorm', displayName: 'Ana Checkstorm', description: 'Checks arrive in waves for players who like sharp attacks.', tags: ['chess', 'streamer', 'attack', 'creator'], aliases: ['anna-cramling', 'ana'] },
  { slug: 'dina-knight-dance', displayName: 'Dina Knight Dance', description: 'Knight jumps and tricky forks keep every move tactical.', tags: ['chess', 'streamer', 'knight', 'creator'], aliases: ['dina', 'dina-belenkaya'] },
  { slug: 'gotham-guess', displayName: 'Gotham Guess', description: 'A puzzle-heavy seed for finding one weird winning move.', tags: ['chess', 'streamer', 'puzzle', 'creator'], aliases: ['gothamchess', 'levy'] },
  { slug: 'eric-rosen-trap', displayName: 'Eric Rosen Trap', description: 'Quiet-looking moves hide sudden mate nets and piece traps.', tags: ['chess', 'streamer', 'trap', 'creator'], aliases: ['eric-rosen', 'rosen'] },
  { slug: 'agadmator-saga', displayName: 'Agadmator Saga', description: 'A story-rich seed where every capture feels like a classic game.', tags: ['chess', 'youtube', 'classic', 'creator'], aliases: ['agadmator'] },
  { slug: 'chessbrah-brawl', displayName: 'Chessbrah Brawl', description: 'An aggressive tempo race built for blitz chaos.', tags: ['chess', 'streamer', 'blitz', 'creator'], aliases: ['chessbrah', 'aman-hambleton', 'eric-hansen'] },
  { slug: 'naroditsky-lesson', displayName: 'Naroditsky Lesson', description: 'A clean instructional seed with tactics that reward calculation.', tags: ['chess', 'streamer', 'lesson', 'creator'], aliases: ['daniel-naroditsky', 'danya'] },
  { slug: 'anya-sacs', displayName: 'Anya Sacs', description: 'A fearless seed full of quick sacrifices and messy attacks.', tags: ['chess', 'streamer', 'sacrifice', 'creator'], aliases: ['anya-taylor-joy', 'anya'] },
  { slug: 'fabiano-fortress', displayName: 'Fabiano Fortress', description: 'A precise setup where defense and counterpunches matter.', tags: ['chess', 'grandmaster', 'defense'], aliases: ['fabiano', 'caruana'] },
  { slug: 'ding-defense', displayName: 'Ding Defense', description: 'Solid structure hides a sudden central break.', tags: ['chess', 'champion', 'defense'], aliases: ['ding', 'ding-liren'] },
  { slug: 'nepo-nerve', displayName: 'Nepo Nerve', description: 'Fast tactical choices can snowball before anyone stabilizes.', tags: ['chess', 'grandmaster', 'speed'], aliases: ['nepo', 'ian-nepomniachtchi'] },
  { slug: 'judit-attack', displayName: 'Judit Attack', description: 'A sharp attacking seed inspired by fearless attacking chess.', tags: ['chess', 'legend', 'attack'], aliases: ['judit', 'judit-polgar'] },
  { slug: 'kasparov-crush', displayName: 'Kasparov Crush', description: 'Central domination meets ruthless tactical pressure.', tags: ['chess', 'legend', 'attack'], aliases: ['kasparov', 'garry-kasparov'] },
  { slug: 'fischer-random', displayName: 'Fischer Random', description: 'A classic shuffle tribute where opening memory disappears.', tags: ['chess', 'legend', 'shuffle'], aliases: ['fischer', 'bobby-fischer'] },
  { slug: 'pragg-puzzle', displayName: 'Pragg Puzzle', description: 'Young-star energy with exact moves and quick tactics.', tags: ['chess', 'grandmaster', 'puzzle'], aliases: ['pragg', 'praggnanandhaa'] },
  { slug: 'gukesh-grind', displayName: 'Gukesh Grind', description: 'A mature positional fight that can explode at any moment.', tags: ['chess', 'grandmaster', 'strategy'], aliases: ['gukesh'] },
  { slug: 'alireza-attack', displayName: 'Alireza Attack', description: 'Fast-piece activity creates threats before the board settles.', tags: ['chess', 'grandmaster', 'attack'], aliases: ['alireza', 'firouzja'] },
  { slug: 'mrbeast-challenge', displayName: 'MrBeast Challenge', description: 'A huge challenge seed designed for beat-my-score drama.', tags: ['youtube', 'creator', 'challenge', 'viral'], aliases: ['mrbeast'] },
  { slug: 'mkbhd-matte-black', displayName: 'MKBHD Matte Black', description: 'Clean, precise, and stylish with premium tactical lines.', tags: ['youtube', 'tech', 'creator', 'precision'], aliases: ['mkbhd', 'marques-brownlee'] },
  { slug: 'dave2d-desk-setup', displayName: 'Dave2D Desk Setup', description: 'Minimalist lanes reward clean development and sharp timing.', tags: ['youtube', 'tech', 'creator', 'minimal'], aliases: ['dave2d', 'dav2d'] },
  { slug: 'linus-tech-trap', displayName: 'Linus Tech Trap', description: 'A hardware-lab seed where dropped pieces become tactics.', tags: ['youtube', 'tech', 'creator', 'trap'], aliases: ['linus', 'linus-tech-tips'] },
  { slug: 'veritasium-vector', displayName: 'Veritasium Vector', description: 'Science-channel geometry turns diagonals into winning vectors.', tags: ['youtube', 'science', 'creator'], aliases: ['veritasium'] },
  { slug: 'mark-rober-gadget', displayName: 'Mark Rober Gadget', description: 'Clever traps and engineered forks appear from harmless moves.', tags: ['youtube', 'science', 'creator', 'trap'], aliases: ['mark-rober'] },
  { slug: 'matpat-theory', displayName: 'MatPat Theory', description: 'A theory-crafting seed where every line has a hidden twist.', tags: ['youtube', 'creator', 'puzzle'], aliases: ['matpat', 'game-theory'] },
  { slug: 'pewdiepie-panic', displayName: 'PewDiePie Panic', description: 'A meme-speed scramble with wild trades and sudden checks.', tags: ['youtube', 'creator', 'meme', 'chaos'], aliases: ['pewdiepie'] },
  { slug: 'dude-perfect-shot', displayName: 'Dude Perfect Shot', description: 'Long-range piece shots and trick-play tactics define the board.', tags: ['youtube', 'creator', 'trickshot'], aliases: ['dude-perfect'] },
  { slug: 'sidemen-scramble', displayName: 'Sidemen Scramble', description: 'A party-mode seed with messy captures and loud momentum swings.', tags: ['youtube', 'creator', 'group', 'chaos'], aliases: ['sidemen'] },
  { slug: 'ishowspeed-sprint', displayName: 'IShowSpeed Sprint', description: 'Immediate threats force fast decisions from move one.', tags: ['youtube', 'streamer', 'speed', 'creator'], aliases: ['ishowspeed', 'speed'] },
  { slug: 'kai-cenat-chaos', displayName: 'Kai Cenat Chaos', description: 'High-energy pieces collide in an explosive tiny-board fight.', tags: ['streamer', 'influencer', 'creator', 'chaos'], aliases: ['kai-cenat'] },
  { slug: 'xqc-tilt', displayName: 'xQc Tilt', description: 'A volatile seed where one slip flips the entire game.', tags: ['streamer', 'creator', 'chaos'], aliases: ['xqc'] },
  { slug: 'ninja-flank', displayName: 'Ninja Flank', description: 'Quick side attacks reward stealthy piece coordination.', tags: ['streamer', 'creator', 'flank'], aliases: ['ninja'] },
  { slug: 'pokimane-pinch', displayName: 'Pokimane Pinch', description: 'A social-streamer seed with friendly pressure and sneaky tactics.', tags: ['streamer', 'influencer', 'creator'], aliases: ['pokimane'] },
  { slug: 'caseoh-crush', displayName: 'CaseOh Crush', description: 'Heavy piece pressure crowds the board fast.', tags: ['streamer', 'creator', 'pressure'], aliases: ['caseoh'] },
  { slug: 'ludwig-ladder', displayName: 'Ludwig Ladder', description: 'Climb from small threats into a full-on tactical race.', tags: ['streamer', 'youtube', 'creator'], aliases: ['ludwig'] },
  { slug: 'moist-critical-mate', displayName: 'MoistCr1TiKaL Mate', description: 'Dry humor, wet tactics, and a sudden checkmate threat.', tags: ['youtube', 'streamer', 'creator', 'mate'], aliases: ['moistcritical', 'penguinz0', 'charlie'] },
  { slug: 'logan-paul-prime', displayName: 'Logan Paul Prime', description: 'A flashy challenge seed with risky early material grabs.', tags: ['youtube', 'influencer', 'creator'], aliases: ['logan-paul'] },
  { slug: 'mrwhosetheboss-battery', displayName: 'Mrwhosetheboss Battery', description: 'Coordinated pieces charge up pressure move by move.', tags: ['youtube', 'tech', 'creator'], aliases: ['mrwhosetheboss'] },
  { slug: 'homelander-heatvision', displayName: 'Homelander Heat Vision', description: 'Laser-focused queen lines punish every exposed king.', tags: ['movie', 'tv', 'superhero', 'villain'], aliases: ['homelander'] },
  { slug: 'spiderman-webtrap', displayName: 'Spider-Man Web Trap', description: 'Sticky knight forks and pins make escape difficult.', tags: ['movie', 'superhero', 'trap'], aliases: ['spiderman', 'spider-man'] },
  { slug: 'batman-dark-knight', displayName: 'Batman Dark Knight', description: 'A shadowy defense seed with counterattacks from the corners.', tags: ['movie', 'superhero', 'defense'], aliases: ['batman'] },
  { slug: 'joker-chaos', displayName: 'Joker Chaos', description: 'Unstable tactics turn every safe move into a question.', tags: ['movie', 'villain', 'chaos'], aliases: ['joker'] },
  { slug: 'ironman-arc-reactor', displayName: 'Iron Man Arc Reactor', description: 'Central energy powers sleek piece coordination.', tags: ['movie', 'superhero', 'tech'], aliases: ['ironman', 'iron-man'] },
  { slug: 'thanos-snap', displayName: 'Thanos Snap', description: 'Half the board can vanish after one brutal capture chain.', tags: ['movie', 'villain', 'capture'], aliases: ['thanos'] },
  { slug: 'black-panther-pounce', displayName: 'Black Panther Pounce', description: 'Fast flank strikes leap into the center.', tags: ['movie', 'superhero', 'flank'], aliases: ['black-panther'] },
  { slug: 'deadpool-gambit', displayName: 'Deadpool Gambit', description: 'A fourth-wall-breaking mess of sacrifices and jokes.', tags: ['movie', 'superhero', 'gambit', 'chaos'], aliases: ['deadpool'] },
  { slug: 'wolverine-claws', displayName: 'Wolverine Claws', description: 'Close-range captures shred loose pieces.', tags: ['movie', 'superhero', 'capture'], aliases: ['wolverine'] },
  { slug: 'oppenheimer-chain', displayName: 'Oppenheimer Chain', description: 'One central break triggers a massive tactical chain reaction.', tags: ['movie', 'drama', 'tactical'], aliases: ['oppenheimer'] },
  { slug: 'barbie-dreamhouse', displayName: 'Barbie Dreamhouse', description: 'Bright-looking squares hide surprisingly sharp traps.', tags: ['movie', 'pop', 'trap'], aliases: ['barbie'] },
  { slug: 'godzilla-stomp', displayName: 'Godzilla Stomp', description: 'Heavy pieces stomp through cramped files.', tags: ['movie', 'monster', 'attack'], aliases: ['godzilla'] },
  { slug: 'john-wick-focus', displayName: 'John Wick Focus', description: 'Precise captures reward relentless calculation.', tags: ['movie', 'action', 'capture'], aliases: ['john-wick'] },
  { slug: 'neo-matrix-dodge', displayName: 'Neo Matrix Dodge', description: 'A slick evasive seed full of impossible-looking escapes.', tags: ['movie', 'sci-fi', 'defense'], aliases: ['neo', 'matrix'] },
  { slug: 'darth-vader-fork', displayName: 'Darth Vader Fork', description: 'Dark-side pressure pins pieces before the fork lands.', tags: ['movie', 'sci-fi', 'villain', 'fork'], aliases: ['darth-vader', 'vader'] },
  { slug: 'yoda-endgame', displayName: 'Yoda Endgame', description: 'Small-board wisdom turns quiet moves into wins.', tags: ['movie', 'sci-fi', 'endgame'], aliases: ['yoda'] },
  { slug: 'harry-potter-spell', displayName: 'Harry Potter Spell', description: 'Magical diagonals and surprise saves keep the board alive.', tags: ['movie', 'fantasy', 'tactical'], aliases: ['harry-potter'] },
  { slug: 'voldemort-horcrux', displayName: 'Voldemort Horcrux', description: 'A villain seed where the king refuses to stay dead.', tags: ['movie', 'fantasy', 'villain'], aliases: ['voldemort'] },
  { slug: 'shrek-swamp', displayName: 'Shrek Swamp', description: 'Messy center squares make every trade feel like swamp chess.', tags: ['movie', 'animated', 'chaos'], aliases: ['shrek'] },
  { slug: 'elsa-freeze', displayName: 'Elsa Freeze', description: 'Frozen files lock pieces until one break opens everything.', tags: ['movie', 'animated', 'positional'], aliases: ['elsa', 'frozen'] },
  { slug: 'naruto-shadow-clone', displayName: 'Naruto Shadow Clone', description: 'Multiple threats appear at once from hyperactive piece jumps.', tags: ['anime', 'ninja', 'attack'], aliases: ['naruto'] },
  { slug: 'luffy-gear-five', displayName: 'Luffy Gear Five', description: 'Cartoon chaos and flexible attacks stretch the board.', tags: ['anime', 'pirate', 'chaos'], aliases: ['luffy', 'one-piece'] },
  { slug: 'zoro-three-swords', displayName: 'Zoro Three Swords', description: 'Three-direction attacks cut through the center.', tags: ['anime', 'pirate', 'attack'], aliases: ['zoro'] },
  { slug: 'goku-kamehameha', displayName: 'Goku Kamehameha', description: 'Charged-up threats fire down open lines.', tags: ['anime', 'battle', 'attack'], aliases: ['goku'] },
  { slug: 'vegeta-pride', displayName: 'Vegeta Pride', description: 'Aggressive counters punish anyone who underestimates the position.', tags: ['anime', 'battle', 'counter'], aliases: ['vegeta'] },
  { slug: 'gojo-infinity', displayName: 'Gojo Infinity', description: 'Defense feels untouchable until one perfect tactic lands.', tags: ['anime', 'defense', 'tactical'], aliases: ['gojo'] },
  { slug: 'sukuna-domain', displayName: 'Sukuna Domain', description: 'A ruthless zone-control seed with cutting tactics.', tags: ['anime', 'villain', 'attack'], aliases: ['sukuna'] },
  { slug: 'eren-rumbling', displayName: 'Eren Rumbling', description: 'Pawn waves and heavy pieces rumble across the board.', tags: ['anime', 'attack', 'pawn'], aliases: ['eren'] },
  { slug: 'levi-clean-cut', displayName: 'Levi Clean Cut', description: 'Precise tactical slashes remove loose pieces instantly.', tags: ['anime', 'attack', 'precision'], aliases: ['levi'] },
  { slug: 'tanjiro-waterwheel', displayName: 'Tanjiro Water Wheel', description: 'Flowing attacks rotate from file pressure into diagonals.', tags: ['anime', 'attack', 'tactical'], aliases: ['tanjiro'] },
  { slug: 'nezuko-burst', displayName: 'Nezuko Burst', description: 'A sudden power spike turns defense into offense.', tags: ['anime', 'counter', 'attack'], aliases: ['nezuko'] },
  { slug: 'saitama-one-punch', displayName: 'Saitama One Punch', description: 'One exact capture can end the whole fight.', tags: ['anime', 'meme', 'capture'], aliases: ['saitama'] },
  { slug: 'deku-smash', displayName: 'Deku Smash', description: 'A heroic attacking seed with high-risk breakthrough moves.', tags: ['anime', 'hero', 'attack'], aliases: ['deku'] },
  { slug: 'all-might-smash', displayName: 'All Might Smash', description: 'Big heroic tactics hit the center hard.', tags: ['anime', 'hero', 'attack'], aliases: ['all-might'] },
  { slug: 'light-yagami-plan', displayName: 'Light Yagami Plan', description: 'A devious planning seed where quiet moves sign the verdict.', tags: ['anime', 'strategy', 'villain'], aliases: ['light-yagami', 'kira'] },
  { slug: 'ryuk-apple', displayName: 'Ryuk Apple', description: 'Tempting bait squares lure pieces into trouble.', tags: ['anime', 'trap', 'bait'], aliases: ['ryuk'] },
  { slug: 'edward-alchemy', displayName: 'Edward Alchemy', description: 'Transform material imbalances into tactical compensation.', tags: ['anime', 'strategy', 'tactical'], aliases: ['edward-elric'] },
  { slug: 'itachi-genjutsu', displayName: 'Itachi Genjutsu', description: 'Illusion-like tactics make safe squares disappear.', tags: ['anime', 'ninja', 'trap'], aliases: ['itachi'] },
  { slug: 'sasuke-chidori', displayName: 'Sasuke Chidori', description: 'A piercing attack seed with direct king pressure.', tags: ['anime', 'ninja', 'attack'], aliases: ['sasuke'] },
  { slug: 'ash-pikachu-spark', displayName: 'Ash Pikachu Spark', description: 'Electric forks and friendly chaos start early.', tags: ['anime', 'pokemon', 'fork'], aliases: ['ash', 'pikachu'] },
  { slug: 'taylor-swift-era', displayName: 'Taylor Swift Era', description: 'A tour-sized seed where the position changes eras fast.', tags: ['music', 'influencer', 'pop', 'viral'], aliases: ['taylor-swift'] },
  { slug: 'drake-hotline', displayName: 'Drake Hotline', description: 'Switch sides of the board for sudden counterplay.', tags: ['music', 'influencer', 'pop'], aliases: ['drake'] },
  { slug: 'beyonce-formation', displayName: 'Beyoncé Formation', description: 'Pieces form up with tempo and hit in perfect sync.', tags: ['music', 'influencer', 'pop'], aliases: ['beyonce'] },
  { slug: 'rihanna-diamond', displayName: 'Rihanna Diamond', description: 'A sparkling setup with diagonal pressure and clean tactics.', tags: ['music', 'influencer', 'pop'], aliases: ['rihanna'] },
  { slug: 'messi-through-ball', displayName: 'Messi Through Ball', description: 'Thread tiny passing lanes for unstoppable attacking chances.', tags: ['sports', 'influencer', 'precision'], aliases: ['messi', 'lionel-messi'] },
  { slug: 'ronaldo-siuu', displayName: 'Ronaldo SIUU', description: 'Explosive jumps and direct attacks go straight for glory.', tags: ['sports', 'influencer', 'attack'], aliases: ['ronaldo', 'cristiano'] },
  { slug: 'lebron-chasedown', displayName: 'LeBron Chasedown', description: 'Defense turns into transition attacks in one move.', tags: ['sports', 'influencer', 'defense'], aliases: ['lebron', 'lebron-james'] },
  { slug: 'curry-deep-three', displayName: 'Curry Deep Three', description: 'Long-range queen shots punish lazy development.', tags: ['sports', 'influencer', 'range'], aliases: ['curry', 'steph-curry'] },
  { slug: 'serena-serve', displayName: 'Serena Serve', description: 'A powerful first move sets up relentless pressure.', tags: ['sports', 'influencer', 'attack'], aliases: ['serena', 'serena-williams'] },
  { slug: 'zendaya-spotlight', displayName: 'Zendaya Spotlight', description: 'Center-stage pieces coordinate with style and precision.', tags: ['celebrity', 'influencer', 'style'], aliases: ['zendaya'] },
  { slug: 'kim-kardashian-buzz', displayName: 'Kim Kardashian Buzz', description: 'A viral seed built for big reactions and quick rematches.', tags: ['influencer', 'celebrity', 'viral'], aliases: ['kim-kardashian'] },
  { slug: 'charli-dance-rush', displayName: 'Charli Dance Rush', description: 'Tempo moves dance across the tiny board.', tags: ['influencer', 'tiktok', 'speed'], aliases: ['charli-damelio'] },
  { slug: 'khaby-silent-check', displayName: 'Khaby Silent Check', description: 'Simple moves solve complicated-looking tactical problems.', tags: ['influencer', 'tiktok', 'puzzle'], aliases: ['khaby-lame'] },
  { slug: 'addison-viral', displayName: 'Addison Viral', description: 'Fast social momentum turns a small tactic into a big swing.', tags: ['influencer', 'tiktok', 'viral'], aliases: ['addison-rae'] },
  { slug: 'hasbulla-haymaker', displayName: 'Hasbulla Haymaker', description: 'Tiny-board punches land harder than expected.', tags: ['influencer', 'meme', 'attack'], aliases: ['hasbulla'] },
  { slug: 'prime-bottle-brawl', displayName: 'Prime Bottle Brawl', description: 'Flashy branding energy meets chaotic capture races.', tags: ['influencer', 'viral', 'chaos'], aliases: ['prime'] },
];

export function normalizeSeedSlug(input: string): string {
  const raw = input.trim().toLowerCase().replace(/[\s_]+/g, '-').replace(/[^a-z0-9-]/g, '').replace(/-+/g, '-').replace(/^-|-$/g, '');
  const match = CURATED_SEEDS.find((seed) => seed.slug === raw || seed.aliases?.includes(raw));
  return match?.slug ?? raw;
}

export function getCuratedSeedBySlug(slug: string): CuratedSeed | null {
  const normalized = normalizeSeedSlug(slug);
  return CURATED_SEEDS.find((seed) => seed.slug === normalized) ?? null;
}

export function getSeedDisplayName(seedSlug: string): string {
  const seed = getCuratedSeedBySlug(seedSlug);
  if (seed) return seed.displayName;
  return normalizeSeedSlug(seedSlug).split('-').filter(Boolean).map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ') || seedSlug;
}
